### PR TITLE
Ae cel 347

### PR DESCRIPTION
**Pull request by philwareublox**
Rob says: Had a quick glance around and it all seems pretty clear to me - easy to navigate around, pretty obvious were all the bits are from your naming convention.  Nice to have a cellular example in the set.

### CODE REVIEW

**Comment by philwareublox** [comment]
Mattia, this is a big change and Rob has reviewed it. He said: Had a quick glance around and it all seems pretty clear to me - easy to navigate around, pretty obvious were all the bits are from your naming convention.  Nice to have a cellular example in the set.
You don't need to do a full review. Just a notice of the pull request. I'll merge when you approve.

**Comment by rebatoma** [comment]
the current version look OK to me. 
I think we can proceed with the mergin on the master here.

**Comment by rebatoma** [comment]
should we close/drop this pull request?

**Comment by philwareublox** [comment]
Yes.

**Pull request closed without merging**
